const wordsToGuess = [
  "canto",
  "caspa",
  "cenar",
  "cocer",
  "comer",
  "coser",
  "creer",
  "gusta",
  "habla",
  "poner",
  "resta",
  "rubia",
  "saber",
  "sitio",
  "tener",
  "tomar",
  "vocal",
  "balsa",
  "calma",
  "salud",
  "coche",
  "tango",
  "santo",
  'cielo',
  'faena',
  'tenor',
  'falsa',
  'falso',
  'avion',
  'peras',
  'largo',
  'criar',
  'fumar',
  'mamar',
  'ambar',
  'libra',
  'rural',
  'ayuda',
  'grito',
  'grita',
  'arduo',
  'dolor',
  'doler',
  'lento',
  'plomo',
  'liman',
  'limar',
  'mimar',
  'rimar',
  'atril',
  'mundo',
  'mojar',
  'fuego',
  'nieto',
  'volco',
  'manco',
  'abaco',
  'feria',
  'errar',
  'jalea',
];

// Check if a word is more than once
// const wordToUpperCase = wordsToGuess.map(word => word.toLowerCase());
// const filtrado = wordToUpperCase.filter((word, index) => { if (index !== wordToUpperCase.indexOf(word) || word.length !== 5) return word })
// console.log("Repeated or not valid length ->",[...new Set(filtrado)])